### ISSUE TITLE
Let's stop using PHP sessions

### ISSUE THREAD

**Issue by JakeBooher** [ezrpg/ezRPG-1.2.x#54]
Let's create our own internal session system.

**Comment by deohnas** [comment]
Could you elaborate on what you want to do, are we talking about an different API , like a Session class. Or do you mean how we store the session data?

**Comment by uaktags** [comment]
Maybe come back to this after 1.3, unless there's a glaring need, it's probably less necessary in our current state.

**Comment by JakeBooher** [comment]
Doing something like this would be fairly important. Right now using PHP sessions it is impossible to have a "keep me logged in" button, as the cookie created for these only last until the browser is closed.

**Comment by uaktags** [comment]
That sounds a bit different of a need then "let's create our own internal session system". I'd still rate that issue to be less of a problem and more of a nuisance and probably be easily fixable within a hook and the login module. But otherwise a full rework of session handling should still probably be pushed off until atleast we clean up the code, fix the more glaring issues, etc.

**Comment by deohnas** [comment]
I agree with @uaktags

**Comment by uaktags** [comment]
Closing for now, we can come back to it later if the need arises.
