### ISSUE TITLE
Modules and Cache

### ISSUE THREAD

**Issue by vinnycrazzy** [ezrpg/ezRPG-1.2.x#58]
#Well, the 2 days I was doing a module, but even after activated and all configured in the database, the module does not start with the URL. Index.php?mod=Example. But to my surprise, after 2 days the module ran out of nowhere, after I put it in the url again. Is there any kind of module cache?

Changing the subject, I'm developing a new theme using Semantic-UI
[Print](https://drive.google.com/file/d/0B0gXu5FuL6RfOWJHc2w5eEpBYms/view?usp=sharing)

Another doubt, do you still have plans to continue this engine?

**Comment by uaktags** [comment]
I am still actively continuing with this engine. If you can, please provide a series of reproduciable steps that I can try to figure out what/where the issue is that you're experiencing. 

For instance, the things that aren't clear are
"the module ran out of nowhere", "the module does not start with the URL", etc. 

Modules, in their current form, need to be installed and Activated within the Admin Panel. Until they are, they can't be visited when hitting the link.

**Comment by deohnas** [comment]
We have plans on continuing the development. @uaktags have setup a roadmap on the official forums http://community.ezrpgproject.net/threads/tentative-roadmap-for-1-2-x-series.384/#post-2108 towards and 1.3 release, with bug fixes, refactoring of legacy code and in general many improvements as well as quality assurance.

**Comment by vinnycrazzy** [comment]
Good morning, sorry for English, I'm using the Google translator!
**uaktags** I tried to say that, the module did not start with a URL!
But anyway, thanks **deohnas**, I'll look at this.
And thanks **uaktags**  I am very happy that this egine still survives, no more modern rpg scripts are found on the internet.

Changing the subject, what do you think of the core of the engine being by codeigniter?

**Comment by deohnas** [comment]
It's good to hear from people using it @vinnycrazzy keeps us motivated :-)
